-- Sample data Generated by AI

-- =====================================================================================
-- Sample Data for University Database Management System
-- =====================================================================================
-- Description: Comprehensive sample data for all tables in the university database
-- Version: 1.0
-- Date: 20 August 2025
-- =====================================================================================

-- Clear existing data (if any) in reverse dependency order
DELETE FROM Enrollments;
DELETE FROM Course_Offering_Days;
DELETE FROM Course_Offerings;
DELETE FROM Student_Addresses;
DELETE FROM Student_Minors;
DELETE FROM Students;
DELETE FROM Classrooms;
DELETE FROM Courses;
DELETE FROM Faculty;
DELETE FROM Minors;
DELETE FROM Majors;
DELETE FROM Departments;

-- Reset sequences
ALTER SEQUENCE departments_department_id_seq RESTART WITH 1;
ALTER SEQUENCE faculty_faculty_id_seq RESTART WITH 1;
ALTER SEQUENCE classrooms_classroom_id_seq RESTART WITH 1;
ALTER SEQUENCE majors_major_id_seq RESTART WITH 1;
ALTER SEQUENCE minors_minor_id_seq RESTART WITH 1;
ALTER SEQUENCE students_student_id_seq RESTART WITH 1;
ALTER SEQUENCE student_addresses_address_id_seq RESTART WITH 1;
ALTER SEQUENCE course_offerings_offering_id_seq RESTART WITH 1;
ALTER SEQUENCE enrollments_enrollment_id_seq RESTART WITH 1;

-- =====================================================================================
-- DEPARTMENTS DATA
-- =====================================================================================

INSERT INTO Departments (Department_Name) VALUES 
    ('Computer Science'),
    ('Mathematics'),
    ('English Literature'),
    ('Business Administration'),
    ('Mechanical Engineering'),
    ('Electrical Engineering'),
    ('Psychology'),
    ('Biology'),
    ('Chemistry'),
    ('Physics');

-- =====================================================================================
-- FACULTY DATA
-- =====================================================================================

INSERT INTO Faculty (First_Name, Last_Name, Department_ID) VALUES 
    -- Computer Science Faculty
    ('Sarah', 'Johnson', 1),
    ('Michael', 'Chen', 1),
    ('Emily', 'Rodriguez', 1),
    ('David', 'Park', 1),
    
    -- Mathematics Faculty
    ('Robert', 'Wilson', 2),
    ('Lisa', 'Anderson', 2),
    ('James', 'Thompson', 2),
    
    -- English Literature Faculty
    ('Patricia', 'Brown', 3),
    ('Christopher', 'Davis', 3),
    ('Amanda', 'Miller', 3),
    
    -- Business Administration Faculty
    ('Jennifer', 'Garcia', 4),
    ('William', 'Martinez', 4),
    ('Michelle', 'Taylor', 4),
    
    -- Mechanical Engineering Faculty
    ('Kevin', 'Lee', 5),
    ('Rachel', 'White', 5),
    
    -- Electrical Engineering Faculty
    ('Thomas', 'Harris', 6),
    ('Nicole', 'Clark', 6),
    
    -- Psychology Faculty
    ('Daniel', 'Lewis', 7),
    ('Karen', 'Walker', 7),
    
    -- Biology Faculty
    ('Steven', 'Hall', 8),
    ('Laura', 'Young', 8),
    
    -- Chemistry Faculty
    ('Mark', 'King', 9),
    ('Angela', 'Wright', 9),
    
    -- Physics Faculty
    ('Charles', 'Lopez', 10),
    ('Stephanie', 'Hill', 10);

-- =====================================================================================
-- CLASSROOMS DATA
-- =====================================================================================

INSERT INTO Classrooms (Building_Number, Building_Block, Room_Number, Room_Capacity) VALUES
    -- Science Building (101)
    (101, 'A', 101, 30),
    (101, 'A', 102, 25),
    (101, 'A', 201, 40),
    (101, 'A', 202, 35),
    (101, 'B', 101, 50),
    (101, 'B', 102, 45),
    (101, 'B', 201, 60),
    (101, 'B', 202, 55),
    
    -- Engineering Building (102)
    (102, 'A', 101, 30),
    (102, 'A', 102, 25),
    (102, 'A', 201, 35),
    (102, 'B', 101, 40),
    (102, 'B', 102, 45),
    (102, 'B', 201, 50),
    
    -- Liberal Arts Building (103)
    (103, 'A', 101, 25),
    (103, 'A', 102, 30),
    (103, 'A', 201, 35),
    (103, 'B', 101, 40),
    (103, 'B', 102, 45),
    (103, 'B', 201, 50),
    
    -- Business Building (104)
    (104, 'A', 101, 60),
    (104, 'A', 102, 55),
    (104, 'A', 201, 70),
    (104, 'B', 101, 65),
    (104, 'B', 102, 60);

-- =====================================================================================
-- COURSES DATA
-- =====================================================================================

INSERT INTO Courses (Course_Code, Course_Title, Course_Description, Credit_Hours, Department_ID) VALUES 
    -- Computer Science Courses
    ('CS101', 'Introduction to Programming', 'Basic programming concepts using Python', 3, 1),
    ('CS102', 'Data Structures', 'Study of fundamental data structures and algorithms', 4, 1),
    ('CS201', 'Object-Oriented Programming', 'Advanced programming using Java', 3, 1),
    ('CS301', 'Database Systems', 'Design and implementation of database systems', 3, 1),
    ('CS401', 'Software Engineering', 'Software development methodologies and practices', 4, 1),
    
    -- Mathematics Courses
    ('MATH101', 'Calculus I', 'Limits, derivatives, and basic integration', 4, 2),
    ('MATH102', 'Calculus II', 'Advanced integration and series', 4, 2),
    ('MATH201', 'Linear Algebra', 'Vector spaces, matrices, and linear transformations', 3, 2),
    ('MATH301', 'Statistics', 'Probability theory and statistical analysis', 3, 2),
    
    -- English Literature Courses
    ('ENG101', 'Composition I', 'Basic writing and composition skills', 3, 3),
    ('ENG102', 'Composition II', 'Advanced writing and research methods', 3, 3),
    ('ENG201', 'World Literature', 'Survey of global literary works', 3, 3),
    ('ENG301', 'American Literature', 'Study of American literary traditions', 3, 3),
    
    -- Business Administration Courses
    ('BUS101', 'Introduction to Business', 'Overview of business principles and practices', 3, 4),
    ('BUS201', 'Accounting Principles', 'Fundamentals of financial and managerial accounting', 4, 4),
    ('BUS301', 'Marketing Management', 'Marketing strategies and consumer behavior', 3, 4),
    ('BUS401', 'Strategic Management', 'Business strategy and competitive analysis', 4, 4),
    
    -- Mechanical Engineering Courses
    ('ME101', 'Engineering Graphics', 'Technical drawing and CAD fundamentals', 3, 5),
    ('ME201', 'Thermodynamics', 'Energy, heat, and thermodynamic processes', 4, 5),
    ('ME301', 'Fluid Mechanics', 'Behavior of fluids in motion and at rest', 4, 5),
    
    -- Electrical Engineering Courses
    ('EE101', 'Circuit Analysis', 'Basic electrical circuit theory', 4, 6),
    ('EE201', 'Electronics', 'Semiconductor devices and circuits', 4, 6),
    ('EE301', 'Digital Systems', 'Digital logic and computer architecture', 3, 6),
    
    -- Psychology Courses
    ('PSY101', 'General Psychology', 'Introduction to psychological principles', 3, 7),
    ('PSY201', 'Developmental Psychology', 'Human development across the lifespan', 3, 7),
    ('PSY301', 'Abnormal Psychology', 'Mental disorders and psychopathology', 3, 7),
    
    -- Biology Courses
    ('BIO101', 'General Biology', 'Fundamentals of life sciences', 4, 8),
    ('BIO201', 'Cell Biology', 'Structure and function of cells', 3, 8),
    ('BIO301', 'Genetics', 'Principles of heredity and molecular genetics', 4, 8),
    
    -- Chemistry Courses
    ('CHEM101', 'General Chemistry', 'Basic chemical principles and reactions', 4, 9),
    ('CHEM201', 'Organic Chemistry', 'Chemistry of carbon compounds', 4, 9),
    ('CHEM301', 'Physical Chemistry', 'Chemical thermodynamics and kinetics', 4, 9),
    
    -- Physics Courses
    ('PHYS101', 'General Physics I', 'Mechanics and thermodynamics', 4, 10),
    ('PHYS102', 'General Physics II', 'Electricity, magnetism, and waves', 4, 10),
    ('PHYS301', 'Modern Physics', 'Quantum mechanics and relativity', 4, 10);

-- =====================================================================================
-- MAJORS DATA
-- =====================================================================================

INSERT INTO Majors (Major_Name, Department_ID) VALUES 
    ('Computer Science', 1),
    ('Software Engineering', 1),
    ('Mathematics', 2),
    ('Applied Mathematics', 2),
    ('English Literature', 3),
    ('Creative Writing', 3),
    ('Business Administration', 4),
    ('Marketing', 4),
    ('Finance', 4),
    ('Mechanical Engineering', 5),
    ('Electrical Engineering', 6),
    ('Psychology', 7),
    ('Clinical Psychology', 7),
    ('Biology', 8),
    ('Biotechnology', 8),
    ('Chemistry', 9),
    ('Biochemistry', 9),
    ('Physics', 10),
    ('Applied Physics', 10);

-- =====================================================================================
-- MINORS DATA
-- =====================================================================================

INSERT INTO Minors (Minor_Name, Department_ID) VALUES 
    ('Computer Programming', 1),
    ('Data Science', 1),
    ('Statistics', 2),
    ('Technical Writing', 3),
    ('Business Management', 4),
    ('Entrepreneurship', 4),
    ('Engineering Design', 5),
    ('Electronics', 6),
    ('Counseling', 7),
    ('Environmental Science', 8),
    ('Materials Science', 9),
    ('Astronomy', 10);

-- =====================================================================================
-- STUDENTS DATA
-- =====================================================================================

INSERT INTO Students (First_Name, Last_Name, Date_of_Birth, Enrollment_Date, Phone_Number, Email_Address, Major_ID) VALUES 
    ('Alex', 'Johnson', '2003-05-15', '2023-08-25', '5551234567', 'alex.johnson@university.edu', 1),
    ('Maria', 'Garcia', '2002-11-22', '2022-08-22', '5551234568', 'maria.garcia@university.edu', 1),
    ('John', 'Smith', '2003-07-10', '2023-08-25', '5551234569', 'john.smith@university.edu', 3),
    ('Emma', 'Brown', '2002-12-03', '2022-08-22', '5551234570', 'emma.brown@university.edu', 7),
    ('Michael', 'Davis', '2003-03-18', '2023-08-25', '5551234571', 'michael.davis@university.edu', 5),
    ('Sofia', 'Rodriguez', '2002-09-25', '2022-08-22', '5551234572', 'sofia.rodriguez@university.edu', 8),
    ('James', 'Wilson', '2003-01-14', '2023-08-25', '5551234573', 'james.wilson@university.edu', 6),
    ('Isabella', 'Martinez', '2002-08-07', '2022-08-22', '5551234574', 'isabella.martinez@university.edu', 4),
    ('William', 'Anderson', '2003-06-29', '2023-08-25', '5551234575', 'william.anderson@university.edu', 9),
    ('Olivia', 'Taylor', '2002-10-16', '2022-08-22', '5551234576', 'olivia.taylor@university.edu', 2),
    ('Benjamin', 'Thomas', '2003-04-12', '2023-08-25', '5551234577', 'benjamin.thomas@university.edu', 10),
    ('Ava', 'Jackson', '2002-07-28', '2022-08-22', '5551234578', 'ava.jackson@university.edu', 14),
    ('Lucas', 'White', '2003-02-05', '2023-08-25', '5551234579', 'lucas.white@university.edu', 11),
    ('Mia', 'Harris', '2002-11-19', '2022-08-22', '5551234580', 'mia.harris@university.edu', 12),
    ('Alexander', 'Clark', '2003-08-31', '2023-08-25', '5551234581', 'alexander.clark@university.edu', 16),
    ('Charlotte', 'Lewis', '2002-05-08', '2022-08-22', '5551234582', 'charlotte.lewis@university.edu', 3),
    ('Daniel', 'Walker', '2003-09-13', '2023-08-25', '5551234583', 'daniel.walker@university.edu', 18),
    ('Amelia', 'Hall', '2002-12-26', '2022-08-22', '5551234584', 'amelia.hall@university.edu', 7),
    ('Matthew', 'Allen', '2003-01-17', '2023-08-25', '5551234585', 'matthew.allen@university.edu', 1),
    ('Harper', 'Young', '2002-06-04', '2022-08-22', '5551234586', 'harper.young@university.edu', 15);

-- =====================================================================================
-- STUDENT MINORS DATA
-- =====================================================================================

INSERT INTO Student_Minors (Student_ID, Minor_ID) VALUES 
    (1, 3),    -- Alex Johnson - Statistics minor
    (2, 5),    -- Maria Garcia - Business Management minor
    (3, 4),    -- John Smith - Technical Writing minor
    (4, 6),    -- Emma Brown - Entrepreneurship minor
    (5, 8),    -- Michael Davis - Electronics minor
    (6, 10),   -- Sofia Rodriguez - Environmental Science minor
    (7, 7),    -- James Wilson - Engineering Design minor
    (8, 1),    -- Isabella Martinez - Computer Programming minor
    (9, 11),   -- William Anderson - Materials Science minor
    (10, 2),   -- Olivia Taylor - Data Science minor
    (11, 12),  -- Benjamin Thomas - Astronomy minor
    (12, 9),   -- Ava Jackson - Counseling minor
    (15, 3),   -- Alexander Clark - Statistics minor
    (19, 5);   -- Matthew Allen - Business Management minor

-- =====================================================================================
-- STUDENT ADDRESSES DATA
-- =====================================================================================

INSERT INTO Student_Addresses (Student_ID, Street_Number, Street_Name, City, Postal_Code, State_Province) VALUES 
    (1, 123, 'Main Street', 'Springfield', '12345', 'Illinois'),
    (2, 456, 'Oak Avenue', 'Madison', '53706', 'Wisconsin'),
    (3, 789, 'Pine Road', 'Austin', '73301', 'Texas'),
    (4, 321, 'Elm Street', 'Denver', '80202', 'Colorado'),
    (5, 654, 'Maple Drive', 'Seattle', '98101', 'Washington'),
    (6, 987, 'Cedar Lane', 'Portland', '97201', 'Oregon'),
    (7, 147, 'Birch Street', 'Phoenix', '85001', 'Arizona'),
    (8, 258, 'Walnut Avenue', 'Atlanta', '30301', 'Georgia'),
    (9, 369, 'Cherry Road', 'Miami', '33101', 'Florida'),
    (10, 741, 'Spruce Drive', 'Boston', '02101', 'Massachusetts'),
    (11, 852, 'Ash Lane', 'Philadelphia', '19101', 'Pennsylvania'),
    (12, 963, 'Poplar Street', 'Chicago', '60601', 'Illinois'),
    (13, 159, 'Willow Avenue', 'San Francisco', '94101', 'California'),
    (14, 357, 'Hickory Road', 'Los Angeles', '90001', 'California'),
    (15, 486, 'Magnolia Drive', 'New York', '10001', 'New York'),
    (16, 624, 'Sycamore Lane', 'Detroit', '48201', 'Michigan'),
    (17, 135, 'Dogwood Street', 'Nashville', '37201', 'Tennessee'),
    (18, 246, 'Redwood Avenue', 'Salt Lake City', '84101', 'Utah'),
    (19, 579, 'Cypress Road', 'Dallas', '75201', 'Texas'),
    (20, 813, 'Juniper Drive', 'San Diego', '92101', 'California');

-- =====================================================================================
-- COURSE OFFERINGS DATA
-- =====================================================================================

INSERT INTO Course_Offerings (Course_Code, Faculty_ID, Classroom_ID, Semester_Term, Academic_Year, Start_Time, End_Time) VALUES 
    -- Fall 2025 Semester (Term 1)
    ('CS101', 1, 1, 1, 2025, '09:00:00', '10:30:00'),
    ('CS102', 2, 2, 1, 2025, '11:00:00', '12:30:00'),
    ('CS201', 3, 3, 1, 2025, '14:00:00', '15:30:00'),
    ('MATH101', 5, 4, 1, 2025, '08:00:00', '09:30:00'),
    ('MATH102', 6, 5, 1, 2025, '10:00:00', '11:30:00'),
    ('ENG101', 8, 15, 1, 2025, '09:00:00', '10:30:00'),
    ('ENG102', 9, 16, 1, 2025, '11:00:00', '12:30:00'),
    ('BUS101', 11, 21, 1, 2025, '13:00:00', '14:30:00'),
    ('BUS201', 12, 22, 1, 2025, '15:00:00', '16:30:00'),
    ('PSY101', 18, 17, 1, 2025, '10:00:00', '11:30:00'),
    ('BIO101', 20, 6, 1, 2025, '08:00:00', '09:30:00'),
    ('CHEM101', 22, 7, 1, 2025, '14:00:00', '15:30:00'),
    ('PHYS101', 24, 8, 1, 2025, '09:00:00', '10:30:00'),
    ('ME101', 14, 9, 1, 2025, '11:00:00', '12:30:00'),
    ('EE101', 16, 10, 1, 2025, '13:00:00', '14:30:00'),
    
    -- Spring 2025 Semester (Term 2) - Some repeat courses
    ('CS101', 1, 1, 2, 2025, '10:00:00', '11:30:00'),
    ('CS301', 4, 3, 2, 2025, '14:00:00', '15:30:00'),
    ('MATH201', 7, 4, 2, 2025, '09:00:00', '10:30:00'),
    ('ENG201', 10, 18, 2, 2025, '11:00:00', '12:30:00'),
    ('BUS301', 13, 23, 2, 2025, '13:00:00', '14:30:00'),
    ('PSY201', 19, 19, 2, 2025, '15:00:00', '16:30:00'),
    ('BIO201', 21, 6, 2, 2025, '08:00:00', '09:30:00'),
    ('CHEM201', 23, 7, 2, 2025, '10:00:00', '11:30:00'),
    ('PHYS102', 25, 8, 2, 2025, '12:00:00', '13:30:00'),
    ('ME201', 15, 11, 2, 2025, '14:00:00', '15:30:00');

-- =====================================================================================
-- COURSE OFFERING DAYS DATA
-- =====================================================================================

INSERT INTO Course_Offering_Days (Offering_ID, Day_Of_Week) VALUES 
    -- Fall 2025 courses
    (1, 'Monday'), (1, 'Wednesday'), (1, 'Friday'),
    (2, 'Tuesday'), (2, 'Thursday'),
    (3, 'Monday'), (3, 'Wednesday'),
    (4, 'Monday'), (4, 'Wednesday'), (4, 'Friday'),
    (5, 'Tuesday'), (5, 'Thursday'),
    (6, 'Monday'), (6, 'Wednesday'), (6, 'Friday'),
    (7, 'Tuesday'), (7, 'Thursday'),
    (8, 'Monday'), (8, 'Wednesday'),
    (9, 'Tuesday'), (9, 'Thursday'),
    (10, 'Monday'), (10, 'Wednesday'), (10, 'Friday'),
    (11, 'Monday'), (11, 'Wednesday'), (11, 'Friday'),
    (12, 'Tuesday'), (12, 'Thursday'),
    (13, 'Monday'), (13, 'Wednesday'), (13, 'Friday'),
    (14, 'Tuesday'), (14, 'Thursday'),
    (15, 'Monday'), (15, 'Wednesday'),
    
    -- Spring 2025 courses
    (16, 'Tuesday'), (16, 'Thursday'),
    (17, 'Monday'), (17, 'Wednesday'),
    (18, 'Monday'), (18, 'Wednesday'), (18, 'Friday'),
    (19, 'Tuesday'), (19, 'Thursday'),
    (20, 'Monday'), (20, 'Wednesday'),
    (21, 'Tuesday'), (21, 'Thursday'),
    (22, 'Monday'), (22, 'Wednesday'), (22, 'Friday'),
    (23, 'Tuesday'), (23, 'Thursday'),
    (24, 'Monday'), (24, 'Wednesday'), (24, 'Friday'),
    (25, 'Tuesday'), (25, 'Thursday');

-- =====================================================================================
-- ENROLLMENTS DATA
-- =====================================================================================

INSERT INTO Enrollments (Student_ID, Offering_ID, Final_Grade) VALUES 
    -- Fall 2025 enrollments with grades
    (1, 1, '9.2'),   -- Alex Johnson - CS101
    (1, 4, '8.7'),   -- Alex Johnson - MATH101
    (1, 6, '8.9'),   -- Alex Johnson - ENG101
    (2, 1, '9.5'),   -- Maria Garcia - CS101
    (2, 2, '9.1'),   -- Maria Garcia - CS102
    (2, 5, '8.8'),   -- Maria Garcia - MATH102
    (3, 4, '9.3'),   -- John Smith - MATH101
    (3, 6, '9.7'),   -- John Smith - ENG101
    (3, 7, '9.2'),   -- John Smith - ENG102
    (4, 10, '8.9'),  -- Emma Brown - PSY101
    (4, 6, '8.6'),   -- Emma Brown - ENG101
    (4, 8, '8.4'),   -- Emma Brown - BUS101
    (5, 14, '9.1'),  -- Michael Davis - ME101
    (5, 4, '8.8'),   -- Michael Davis - MATH101
    (5, 13, '8.5'),  -- Michael Davis - PHYS101
    (6, 11, '9.4'),  -- Sofia Rodriguez - BIO101
    (6, 12, '9.0'),  -- Sofia Rodriguez - CHEM101
    (6, 4, '8.7'),   -- Sofia Rodriguez - MATH101
    (7, 15, '8.9'),  -- James Wilson - EE101
    (7, 5, '8.6'),   -- James Wilson - MATH102
    (7, 13, '8.3'),  -- James Wilson - PHYS101
    (8, 8, '9.2'),   -- Isabella Martinez - BUS101
    (8, 9, '8.8'),   -- Isabella Martinez - BUS201
    (8, 6, '8.5'),   -- Isabella Martinez - ENG101
    (9, 12, '9.0'),  -- William Anderson - CHEM101
    (9, 5, '8.7'),   -- William Anderson - MATH102
    (9, 13, '8.4'),   -- William Anderson - PHYS101
    (10, 4, '9.6'),  -- Olivia Taylor - MATH101
    (10, 5, '9.3'),  -- Olivia Taylor - MATH102
    (10, 1, '8.9'),  -- Olivia Taylor - CS101
    
    -- Spring 2025 enrollments (some with grades, some ongoing)
    (1, 17, '8.8'),  -- Alex Johnson - CS301
    (1, 18, '9.0'),  -- Alex Johnson - MATH201
    (2, 16, '9.3'),  -- Maria Garcia - CS101 (repeat)
    (2, 17, '9.1'),  -- Maria Garcia - CS301
    (3, 18, '9.4'),  -- John Smith - MATH201
    (3, 19, '9.2'),  -- John Smith - ENG201
    (4, 21, '8.7'),  -- Emma Brown - PSY201
    (4, 20, '8.5'),  -- Emma Brown - BUS301
    (5, 25, '8.9'),  -- Michael Davis - ME201
    (6, 22, '9.2'),  -- Sofia Rodriguez - BIO201
    (6, 23, '8.8'),  -- Sofia Rodriguez - CHEM201
    (7, 24, '8.6'),  -- James Wilson - PHYS102
    (8, 20, '8.9'),  -- Isabella Martinez - BUS301
    (9, 23, '8.7'),  -- William Anderson - CHEM201
    (10, 18, '9.5'), -- Olivia Taylor - MATH201
    (11, 24, '8.4'), -- Benjamin Thomas - PHYS102
    (12, 22, '9.1'), -- Ava Jackson - BIO201
    (13, 17, '8.3'), -- Lucas White - CS301
    (14, 21, '8.8'), -- Mia Harris - PSY201
    (15, 23, '8.6'); -- Alexander Clark - CHEM201